version: "3"
services:

  python:
    container_name: python3
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./app:/usr/src/app
    restart: always
