version: "3"
services:

  python:
    container_name: python-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5000" # By default, many Flask applications run on port 5000 (5001 on host to avoid troubles)
      - "8001:80"
      - "7001:7000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - ./app:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always
